// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VoxelSpace.Api.Infrastructure.Data;

#nullable disable

namespace VoxelSpace.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VoxelDbContext))]
    partial class VoxelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("MassaInicialKg")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)");

                    b.Property<int>("Material")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("COMPONENTES_ESPACIAIS", (string)null);

                    b.HasDiscriminator<string>("TIPO").HasValue("ComponenteEspacial");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Execucoes.ExecucaoOtimizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponenteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double?>("EffectiveVolfrac")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("GridX")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("GridY")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("GridZ")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MassaFinalKg")
                        .HasPrecision(12, 4)
                        .HasColumnType("DECIMAL(12,4)");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NComponentsDiscarded")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("ReducaoPct")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("SolverElapsedS")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("VolumeDesignSpaceMm3")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("VolumeFinalMm3")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("Watertight")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Status");

                    b.ToTable("EXECUCOES_OTIMIZACAO", (string)null);
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Execucoes.IteracaoOtimizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Change")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Compliance")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("ComplianceDelta")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("ExecucaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumeroIteracao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("TempoIteracaoS")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VolumeFracao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId", "NumeroIteracao");

                    b.ToTable("ITERACOES_OTIMIZACAO", (string)null);
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Regioes.RegiaoFronteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExecucaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("Fx")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Fy")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Fz")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("GEOMETRIA")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.Property<int>("TipoCondicao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId");

                    b.ToTable("REGIOES_FRONTEIRA", (string)null);

                    b.HasDiscriminator<string>("GEOMETRIA").HasValue("RegiaoFronteira");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Componentes.PainelSolar", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial");

                    b.Property<double>("AreaM2")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PotenciaW")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasDiscriminator().HasValue("PAINEL_SOLAR");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Componentes.SuporteAntena", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial");

                    b.Property<double>("FrequenciaGhz")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasDiscriminator().HasValue("SUPORTE_ANTENA");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Componentes.SuporteEstrutural", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial");

                    b.Property<double>("CargaSuportadaKn")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasDiscriminator().HasValue("SUPORTE_ESTRUTURAL");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Regioes.RegiaoCaixa", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Regioes.RegiaoFronteira");

                    b.Property<double>("MaxX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("MaxY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("MaxZ")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("MinX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("MinY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("MinZ")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasDiscriminator().HasValue("CAIXA");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Regioes.RegiaoEsferica", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Regioes.RegiaoFronteira");

                    b.Property<double>("CentroX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CentroY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CentroZ")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Raio")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasDiscriminator().HasValue("ESFERA");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Regioes.RegiaoFace", b =>
                {
                    b.HasBaseType("VoxelSpace.Api.Domain.Regioes.RegiaoFronteira");

                    b.Property<double>("AreaFaceMm2")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("EspessuraMm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("Face")
                        .HasColumnType("NUMBER(10)");

                    b.HasDiscriminator().HasValue("FACE");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Execucoes.ExecucaoOtimizacao", b =>
                {
                    b.HasOne("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial", "Componente")
                        .WithMany("Execucoes")
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VoxelSpace.Api.Domain.Execucoes.ParametrosOtimizacao", "Parametros", b1 =>
                        {
                            b1.Property<int>("ExecucaoOtimizacaoId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<int>("Maxloop")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("PARAM_MAXLOOP");

                            b1.Property<int>("Nelx")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("PARAM_NELX");

                            b1.Property<int>("Nely")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("PARAM_NELY");

                            b1.Property<int>("Nelz")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("PARAM_NELZ");

                            b1.Property<double>("Penal")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("PARAM_PENAL");

                            b1.Property<double>("Pitch")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("PARAM_PITCH");

                            b1.Property<double>("Rmin")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("PARAM_RMIN");

                            b1.Property<double>("Tolx")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("PARAM_TOLX");

                            b1.Property<double>("Volfrac")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("PARAM_VOLFRAC");

                            b1.HasKey("ExecucaoOtimizacaoId");

                            b1.ToTable("EXECUCOES_OTIMIZACAO");

                            b1.WithOwner()
                                .HasForeignKey("ExecucaoOtimizacaoId");
                        });

                    b.Navigation("Componente");

                    b.Navigation("Parametros")
                        .IsRequired();
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Execucoes.IteracaoOtimizacao", b =>
                {
                    b.HasOne("VoxelSpace.Api.Domain.Execucoes.ExecucaoOtimizacao", "Execucao")
                        .WithMany("Iteracoes")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execucao");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Regioes.RegiaoFronteira", b =>
                {
                    b.HasOne("VoxelSpace.Api.Domain.Execucoes.ExecucaoOtimizacao", "Execucao")
                        .WithMany("Regioes")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execucao");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Componentes.ComponenteEspacial", b =>
                {
                    b.Navigation("Execucoes");
                });

            modelBuilder.Entity("VoxelSpace.Api.Domain.Execucoes.ExecucaoOtimizacao", b =>
                {
                    b.Navigation("Iteracoes");

                    b.Navigation("Regioes");
                });
#pragma warning restore 612, 618
        }
    }
}
